easy:
  name: "Fácil"
  options_per_level: 4
  bombs_per_level: 1
  total_levels: 9
  multipliers: [1.31, 1.75, 2.33, 3.11, 4.15, 5.53, 7.38, 9.84, 13.12]

medium:
  name: "Médio"
  options_per_level: 3
  bombs_per_level: 1
  total_levels: 9
  multipliers: [1.48, 2.22, 3.33, 5.00, 7.50, 11.25, 16.87, 25.31, 37.96]

hard:
  name: "Difícil"
  options_per_level: 2
  bombs_per_level: 1
  total_levels: 9
  multipliers: [1.98, 3.96, 7.92, 15.84, 31.68, 63.36, 126.72, 253.44, 506.88]

expert:
  name: "Especialista"
  options_per_level: 3
  bombs_per_level: 2
  total_levels: 9
  multipliers: [2.97, 8.91, 26.73, 80.19, 240.57, 721.71, 2165.13, 6495.39, 19486.17]

legendary:
  name: "Lendário"
  options_per_level: 4
  bombs_per_level: 3
  total_levels: 9
  multipliers: [1.31, 1.75, 2.33, 3.11, 4.15, 5.53, 7.38, 9.84, 13.12]
